# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# load configuration
# -----------------------------------------------------
configfile: "config/config.yaml"

# Helper to build target paths
SAMPLES = SAMPLES, = glob_wildcards(os.path.join(config["samples_dir"], "{sample}.csv"))
DATA = config["data_dir"]
RESULTS = config["results_dir"]

# load rules
# -----------------------------------------------------
include: "rules/count_hybrids.smk"


# optional messages, log and error handling
# -----------------------------------------------------
onstart:
    print("\n--- Analysis started ---\n")


onsuccess:
    print("\n--- Workflow finished! ---\n")


onerror:
    print("\n--- An error occurred! ---\n")


# target rules
# -----------------------------------------------------
rule all:
    input:
        # Use expand to create concrete file lists for the DAG
        expand(f"{RESULTS}/{{sample}}.aggregate.csv", sample=SAMPLES)